_target_: src.models.unet_nyu_module.UNetNYUModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0004
  weight_decay: 0.02

scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  _partial_: true
  max_lr: 0.001
  epochs: 20
  steps_per_epoch: 400

net:
  _target_: src.models.components.unet.UNet
  trainable_encoder: true

# compile model for faster training with pytorch 2.0
compile: false
