# @package _global_

defaults:
  - _self_
  - data: nyu
  - model: nyu_efffnet
  - callbacks: default
  - logger: wandb
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

  - experiment: nyu_efffnet

  - hparams_search: null

  - optional local: default

  - debug: null

task_name: "quant"

tags: ["dev"]

test: True

seed: 42

ckpt_path: null

inference_speed: True

quantization:
  methods:
    # - "fuse_bn"
    - "ptq"
    - "qat"
  ptq:
    batches_limit: 250
  qat:
    max_epochs: 10
  quant_config:
    dummy_input_shape: [1, 3, 224, 224]
    is_per_tensor: False
    is_asymmetric: True
    backend: "qnnpack"
    disable_requantization_for_cat: True
    use_cle: True
    overwrite_set_ptq: True
