# @package _global_

defaults:
  - _self_
  - data: fashion_mnist
  - model: fashion_mnist
  - callbacks: default
  - logger: wandb
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

  - experiment: null

  - hparams_search: null

  - optional local: default

  - debug: null

task_name: "train"

tags: ["dev"]

train: True

test: True

ckpt_path: null

seed: 42
